server:
  port: 9000
spring:
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/auth_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    org:
      hibernate:
        type: trace
security:
  oauth2:
    client:
      client-id: mobile
      client-secret: admin
