package com.myprojects.productservice.model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="product"
        ,catalog="hatkholadb"
        , uniqueConstraints = @UniqueConstraint(columnNames="product_id")
)
public class ProductEntity  implements java.io.Serializable {
    private Long id;
    private String productId;
    private String productName;
    private String category;
    private Double oldPrice;
    private Double newPrice;
    private Double costPrice;
    private Integer quantity;
    private String details;
    private Integer review;
    private String image;
//     private Set<Orders> orderses = new HashSet(0);
//     private Set<Cart> carts = new HashSet(0);
//     private Set<Wishlist> wishlists = new HashSet(0);

    public ProductEntity() {
    }


    public ProductEntity(String productId) {
        this.productId = productId;
    }
    public ProductEntity(String productId, String productName, String category, Double oldPrice, Double newPrice, Double costPrice, Integer quantity, String details, Integer review, String image, Set orderses, Set carts, Set wishlists) {
        this.productId = productId;
        this.productName = productName;
        this.category = category;
        this.oldPrice = oldPrice;
        this.newPrice = newPrice;
        this.costPrice = costPrice;
        this.quantity = quantity;
        this.details = details;
        this.review = review;
        this.image = image;
//       this.orderses = orderses;
//       this.carts = carts;
//       this.wishlists = wishlists;
    }

    @Id @GeneratedValue(strategy=IDENTITY)


    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }


    @Column(name="product_id", unique=true, nullable=false, length=20)
    public String getProductId() {
        return this.productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }


    @Column(name="product_name", length=150)
    public String getProductName() {
        return this.productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }


    @Column(name="category", length=50)
    public String getCategory() {
        return this.category;
    }

    public void setCategory(String category) {
        this.category = category;
    }


    @Column(name="old_price", precision=10)
    public Double getOldPrice() {
        return this.oldPrice;
    }

    public void setOldPrice(Double oldPrice) {
        this.oldPrice = oldPrice;
    }


    @Column(name="new_price", precision=10)
    public Double getNewPrice() {
        return this.newPrice;
    }

    public void setNewPrice(Double newPrice) {
        this.newPrice = newPrice;
    }


    @Column(name="cost_price", precision=10)
    public Double getCostPrice() {
        return this.costPrice;
    }

    public void setCostPrice(Double costPrice) {
        this.costPrice = costPrice;
    }


    @Column(name="quantity")
    public Integer getQuantity() {
        return this.quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }


    @Column(name="details", length=65535)
    public String getDetails() {
        return this.details;
    }

    public void setDetails(String details) {
        this.details = details;
    }


    @Column(name="review")
    public Integer getReview() {
        return this.review;
    }

    public void setReview(Integer review) {
        this.review = review;
    }


    @Column(name="image")
    public String getImage() {
        return this.image;
    }
    public void setImage(String image) {
        this.image = image;
    }
}


